import type { Metadata } from "next";
import { Inter, Sora, Turret_Road } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "sonner";
import { Check } from "lucide-react";

const inter = Inter({ subsets: ["latin"] });
const sora = Sora({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sora.className}>
        <Navbar />
        {children}
        <Toaster
          toastOptions={{
            style: {
              background: "#ecfdf3",
              color: "#008a2e",
              fontSize: "18px",
            },
            className: "class",
          }}
          position="bottom-left"
        />
        <Footer />
      </body>
    </html>
  );
}
